[versions]
minecraft = "1.20"
parchment_minecraft = "1.19.3"
parchment_mappings = "2023.03.12"

forge = "1.20-46.0.2"
mixin = "0.8.5"

quilt_loader = "0.18.10"

mdg_plugin = "1.4.1"
mdg_dsl = "1.5.0"
autoservice = "1.1.0"

quilt_loom = "1.2.3"
quilt_licenser = "2.0.1"

forgegradle = "6.0.6"
librarian = "1.2.0"
mixingradle = "0.7.33"

jetbrains_annotations = "24.0.1"

minotaur = "2.8.0"
cursegradle = "1.4.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

forge = { module = "net.minecraftforge:forge", version.ref = "forge" }

jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }

[plugins]

mdg_plugin = { id = "io.github.groovymc.modsdotgroovy", version.ref = "mdg_plugin" }
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
quilt_licenser = { id = "org.quiltmc.gradle.licenser", version.ref = "quilt_licenser" }
forgegradle = { id = "net.minecraftforge.gradle", version.ref = "forgegradle" }
librarian = { id = "org.parchmentmc.librarian.forgegradle", version.ref = "librarian" }
mixingradle = { id = "org.spongepowered.mixin", version.ref = "mixingradle" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
cursegradle = { id = "com.matthewprenger.cursegradle", version.ref = "cursegradle" }
